apprise:
  enabled: true
  url: http://192.168.50.135:10000/notify/fusionn
sqlite:
  enabled: true
  path: ./sqlite.db
translate:
  enabled: true
  provider: llm
deeplx:
  local: false
  url: http://192.168.50.135:1188/v2/translate
llm:
  base: https://api.siliconflow.cn/v1
  endpoint: /chat/completions
  api_key: sk-proj-1234567890
  model: deepseek-ai/DeepSeek-V2.5
  language: Chinese
redis:
  addr: 127.0.0.1:6379
  password: 123456
  db: 0
subset:
  enabled: true
  embed_only: true
style:
  chs_style:
    font_name: "WenQuanYi Micro Hei"
    font_size: 19
    bold: true
    primary_color: "&H00C8C8C8"
    # primary_color: "&H00C5C5C5"
  eng_style:
    font_name: "WenQuanYi Micro Hei"
    font_size: 12
    bold: true
    primary_color: "&H000D94CC"
    # primary_color: "&H0000A0DC"
  margin_left: 10
  margin_right: 10
  margin_vertical: 5
  alignment: 2
  border_style: 1
  wrap_style: "0" # 2: no wrap, 1: wrap
  outline: 0.5
  shadow: 0.3
  secondary_color: "&H0000FFFF"
  outline_color: "&H00000000"
  back_color: "&H00000000"
algo:
  max_overlapping_segments: 3
after:
  reduce_margin: false
  default_margin: "{\\pos(192,272)}"
  eng_margin: "{\\pos(192,283)}"
general:
  force_simplified: true
tvdb:
  enabled: false
  api_key: "1234567890"
gptsubtrans:
  provider: local
sentry:
  enabled: false
  dsn: "https://f626ef5cf2b251daa8aaffe20c2d5fab@o4506674942902272.ingest.us.sentry.io/"
  sample_rate: 0.1
