// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fusionn/internal/database"
	"fusionn/internal/handler"
	"fusionn/internal/server"
	"fusionn/internal/service"
	"fusionn/pkg"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

// NewServer creates a new HTTP server with all its dependencies
func NewServer() (*http.Server, error) {
	databaseService := database.New()
	ffmpeg := service.NewFFMPEG()
	parser := service.NewParser()
	deepL := pkg.NewDeepL()
	convertor := service.NewConvertor(deepL)
	algo := service.NewAlgo()
	apprise := pkg.NewApprise()
	handlerHandler := handler.NewHandler(ffmpeg, parser, convertor, algo, apprise)
	httpServer := server.NewServer(databaseService, handlerHandler)
	return httpServer, nil
}

// wire.go:

// ServerSet is a Wire provider set that includes all server dependencies
var ServerSet = wire.NewSet(pkg.Set, service.Set, database.Set, handler.Set, server.Set)
