// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fusionn/internal/database"
	"fusionn/internal/handler"
	"fusionn/internal/processor"
	"fusionn/internal/server"
	"fusionn/internal/service"
	"fusionn/pkg"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

// NewServer creates a new HTTP server with all its dependencies
func NewServer() (*http.Server, error) {
	databaseService := database.New()
	ffmpeg := service.NewFFMPEG()
	deepL := pkg.NewDeepL()
	convertor := service.NewConvertor(deepL)
	parser := service.NewParser(convertor)
	algo := service.NewAlgo()
	apprise := pkg.NewApprise()
	extractStage := processor.NewExtractStage(ffmpeg)
	parseStage := processor.NewParseStage(parser)
	cleanStage := processor.NewCleanStage(parser)
	mergeStage := processor.NewMergeStage(algo)
	styleStage := processor.NewStyleStage()
	exportStage := processor.NewExportStage()
	notiStage := processor.NewNotiStage(apprise)
	pipeline := handler.ProvidePipeline(extractStage, parseStage, cleanStage, mergeStage, styleStage, exportStage, notiStage)
	handlerHandler := handler.NewHandler(ffmpeg, parser, convertor, algo, apprise, pipeline)
	httpServer := server.NewServer(databaseService, handlerHandler)
	return httpServer, nil
}

// wire.go:

// ServerSet is a Wire provider set that includes all server dependencies
var ServerSet = wire.NewSet(pkg.Set, service.Set, database.Set, handler.Set, server.Set)
