package subtitle

import (
	"fmt"
	"strings"

	"github.com/fusionn/internal/config"
)

const scriptInfoTemplate = `[Script Info]
; Script generated by pysubs2
; https://pypi.python.org/pypi/pysubs2
WrapStyle: 0
ScaledBorderAndShadow: yes
Collisions: Normal
ScriptType: v4.00+

`

const stylesHeaderTemplate = `[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
`

// GenerateStyles generates the complete V4+ Styles section from config.
func GenerateStyles(cfg config.ASSStyleConfig) string {
	var sb strings.Builder

	sb.WriteString(stylesHeaderTemplate)

	// Default style (Primary - Chinese)
	sb.WriteString(generateStyleLine(
		"Default",
		cfg.PrimaryFont,
		cfg.PrimarySize,
		cfg.PrimaryColor,
		cfg,
	))

	// Default_1 style (Secondary - English)
	sb.WriteString(generateStyleLine(
		"Default_1",
		cfg.SecondaryFont,
		cfg.SecondarySize,
		cfg.SecondaryColor,
		cfg,
	))

	sb.WriteString("\n")
	return sb.String()
}

// generateStyleLine generates a single Style: line.
func generateStyleLine(name, font string, size int, color string, cfg config.ASSStyleConfig) string {
	bold := 0
	if cfg.Bold {
		bold = 1
	}

	return fmt.Sprintf(
		"Style: %s,%s,%d,%s,&H0000ffff,&H00000000,&H00000000,%d,0,0,0,90,100,0,0,1,%.1f,%.1f,2,10,10,%d,1\n",
		name,
		font,
		size,
		color,
		bold,
		cfg.Outline,
		cfg.Shadow,
		cfg.MarginV,
	)
}

// GetScriptInfo returns the Script Info template.
func GetScriptInfo() string {
	return scriptInfoTemplate
}
