// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"fusionn/internal/handlers"
	"fusionn/internal/processor"
	"fusionn/internal/repository"
	"fusionn/pkg"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	ffmpeg := repository.NewFFMPEG()
	parser := repository.NewParser()
	deepL := pkg.NewDeepL()
	convertor := repository.NewConvertor(deepL)
	algo := repository.NewAlgo()
	apprise := pkg.NewApprise()
	subtitle := processor.NewSubtitle(ffmpeg, parser, convertor, algo, apprise)
	handler := handlers.NewHandler(subtitle)
	app := NewApp(handler)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
