// Code generated by MockGen. DO NOT EDIT.
// Source: mocks_interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notification "github.com/fusionn/internal/notification"
	queue "github.com/fusionn/internal/queue"
	subtitle "github.com/fusionn/internal/service/subtitle"
	gomock "github.com/golang/mock/gomock"
)

// MockAnalyzerInterface is a mock of AnalyzerInterface interface.
type MockAnalyzerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzerInterfaceMockRecorder
}

// MockAnalyzerInterfaceMockRecorder is the mock recorder for MockAnalyzerInterface.
type MockAnalyzerInterfaceMockRecorder struct {
	mock *MockAnalyzerInterface
}

// NewMockAnalyzerInterface creates a new mock instance.
func NewMockAnalyzerInterface(ctrl *gomock.Controller) *MockAnalyzerInterface {
	mock := &MockAnalyzerInterface{ctrl: ctrl}
	mock.recorder = &MockAnalyzerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzerInterface) EXPECT() *MockAnalyzerInterfaceMockRecorder {
	return m.recorder
}

// AnalyzeVideo mocks base method.
func (m *MockAnalyzerInterface) AnalyzeVideo(ctx context.Context, videoPath string) (*subtitle.AnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeVideo", ctx, videoPath)
	ret0, _ := ret[0].(*subtitle.AnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeVideo indicates an expected call of AnalyzeVideo.
func (mr *MockAnalyzerInterfaceMockRecorder) AnalyzeVideo(ctx, videoPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeVideo", reflect.TypeOf((*MockAnalyzerInterface)(nil).AnalyzeVideo), ctx, videoPath)
}

// ExtractSubtitles mocks base method.
func (m *MockAnalyzerInterface) ExtractSubtitles(ctx context.Context, analysis *subtitle.AnalysisResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSubtitles", ctx, analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractSubtitles indicates an expected call of ExtractSubtitles.
func (mr *MockAnalyzerInterfaceMockRecorder) ExtractSubtitles(ctx, analysis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSubtitles", reflect.TypeOf((*MockAnalyzerInterface)(nil).ExtractSubtitles), ctx, analysis)
}

// MockNotificationClientInterface is a mock of NotificationClientInterface interface.
type MockNotificationClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientInterfaceMockRecorder
}

// MockNotificationClientInterfaceMockRecorder is the mock recorder for MockNotificationClientInterface.
type MockNotificationClientInterfaceMockRecorder struct {
	mock *MockNotificationClientInterface
}

// NewMockNotificationClientInterface creates a new mock instance.
func NewMockNotificationClientInterface(ctrl *gomock.Controller) *MockNotificationClientInterface {
	mock := &MockNotificationClientInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClientInterface) EXPECT() *MockNotificationClientInterfaceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockNotificationClientInterface) Send(ctx context.Context, title, body string, ntype notification.Type) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, title, body, ntype)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationClientInterfaceMockRecorder) Send(ctx, title, body, ntype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationClientInterface)(nil).Send), ctx, title, body, ntype)
}

// MockQueueClientInterface is a mock of QueueClientInterface interface.
type MockQueueClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQueueClientInterfaceMockRecorder
}

// MockQueueClientInterfaceMockRecorder is the mock recorder for MockQueueClientInterface.
type MockQueueClientInterfaceMockRecorder struct {
	mock *MockQueueClientInterface
}

// NewMockQueueClientInterface creates a new mock instance.
func NewMockQueueClientInterface(ctrl *gomock.Controller) *MockQueueClientInterface {
	mock := &MockQueueClientInterface{ctrl: ctrl}
	mock.recorder = &MockQueueClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueClientInterface) EXPECT() *MockQueueClientInterfaceMockRecorder {
	return m.recorder
}

// EnqueueTranslation mocks base method.
func (m *MockQueueClientInterface) EnqueueTranslation(ctx context.Context, job *queue.TranslationJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTranslation", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTranslation indicates an expected call of EnqueueTranslation.
func (mr *MockQueueClientInterfaceMockRecorder) EnqueueTranslation(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTranslation", reflect.TypeOf((*MockQueueClientInterface)(nil).EnqueueTranslation), ctx, job)
}
